name: RSS Feed Collector (Email)

# This workflow is disabled by default. To enable it:
# 1. Uncomment the 'on:' section below
# 2. Configure the required email secrets (EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_TO)
# 3. Optionally disable the default MS Teams workflow

# on:
#   # Run on push to any branch
#   push:
#     branches:
#       - '**'
#   
#   # Schedule to run on weekdays at 9 AM UTC
#   schedule:
#     - cron: '0 9 * * 1-5'  # Monday-Friday at 9 AM UTC
#   
#   # Allow manual trigger
#   workflow_dispatch:

on:
  # Only allow manual trigger by default
  workflow_dispatch:

permissions:
  contents: read

jobs:
  collect-rss-feeds-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Get last successful run time
        id: last-run
        run: |
          # Get the current date
          TODAY=$(date -u +%Y-%m-%d)
          
          # Try to get the last successful run time from this workflow
          LAST_RUN=$(gh run list \
            --workflow="rss-feed-collector-email.yml" \
            --status=success \
            --limit=1 \
            --json updatedAt \
            --jq '.[0].updatedAt' 2>/dev/null || echo "")
          
          if [ -n "$LAST_RUN" ]; then
            LAST_RUN_DATE=$(date -u -d "$LAST_RUN" +%Y-%m-%d)
            LAST_RUN_EPOCH=$(date -u -d "$LAST_RUN" +%s)
            NOW_EPOCH=$(date -u +%s)
            HOURS_SINCE=$((($NOW_EPOCH - $LAST_RUN_EPOCH) / 3600))
            
            # If last run was today, use 24 hours, otherwise use hours since last run
            if [ "$LAST_RUN_DATE" = "$TODAY" ]; then
              echo "hours=24" >> $GITHUB_OUTPUT
              echo "Last successful run was today, fetching articles from last 24 hours"
            else
              # Cap at 168 hours (1 week) to avoid too much data
              if [ $HOURS_SINCE -gt 168 ]; then
                HOURS_SINCE=168
              fi
              echo "hours=$HOURS_SINCE" >> $GITHUB_OUTPUT
              echo "Last successful run was $HOURS_SINCE hours ago, fetching articles since then"
            fi
          else
            # No previous successful run, default to 24 hours
            echo "hours=24" >> $GITHUB_OUTPUT
            echo "No previous successful run found, fetching articles from last 24 hours"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Fetch RSS feeds
        run: |
          python .github/scripts/fetch_rss_feeds.py \
            --config .github/rss-feeds.json \
            --hours ${{ steps.last-run.outputs.hours }} \
            --output rss-output.json \
            --markdown-output rss-output.md
      
      - name: Convert Markdown to HTML
        run: |
          # Convert markdown tables to HTML for better email rendering
          python3 << 'PYTHON_SCRIPT'
          import re
          
          # Read markdown content
          with open('rss-output.md', 'r') as f:
              content = f.read()
          
          html = ['<html>', '<head>', '<style>']
          html.append('''
          body { font-family: Arial, sans-serif; margin: 20px; }
          h2 { color: #0366d6; border-bottom: 2px solid #0366d6; padding-bottom: 5px; }
          table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #0366d6; color: white; }
          tr:nth-child(even) { background-color: #f2f2f2; }
          a { color: #0366d6; text-decoration: none; }
          a:hover { text-decoration: underline; }
          ''')
          html.append('</style>', '</head>', '<body>')
          html.append('<h1>📰 RSS Feed Updates</h1>')
          
          # Split into sections
          sections = content.split('\n## ')
          
          for section in sections:
              if not section.strip():
                  continue
              
              lines = section.split('\n')
              
              # Process section
              in_table = False
              for line in lines:
                  line = line.strip()
                  
                  if not line:
                      continue
                  
                  if line.startswith('##'):
                      html.append(f'<h2>{line.replace("##", "").strip()}</h2>')
                  elif '|' in line and not in_table:
                      # Start of table
                      in_table = True
                      html.append('<table>')
                      # Process header row
                      cells = [cell.strip() for cell in line.split('|') if cell.strip()]
                      html.append('<tr>')
                      for cell in cells:
                          html.append(f'<th>{cell}</th>')
                      html.append('</tr>')
                  elif '|' in line and in_table:
                      if '---' in line:
                          # Skip separator row
                          continue
                      # Data row
                      cells = [cell.strip() for cell in line.split('|') if cell.strip()]
                      html.append('<tr>')
                      for cell in cells:
                          html.append(f'<td>{cell}</td>')
                      html.append('</tr>')
                  elif in_table and '|' not in line:
                      # End of table
                      html.append('</table>')
                      in_table = False
                      if line.startswith('*'):
                          html.append(f'<p><em>{line.replace("*", "")}</em></p>')
                      else:
                          html.append(f'<p>{line}</p>')
                  else:
                      if line.startswith('*'):
                          html.append(f'<p><em>{line.replace("*", "")}</em></p>')
                      else:
                          html.append(f'<p>{line}</p>')
              
              if in_table:
                  html.append('</table>')
          
          html.append('</body>', '</html>')
          
          # Write HTML content
          with open('rss-output.html', 'w') as f:
              f.write('\n'.join(html))
          
          PYTHON_SCRIPT
      
      - name: Send Email
        if: ${{ secrets.EMAIL_TO != '' }}
        run: |
          # Send email using Python's built-in smtplib
          python3 << 'PYTHON_SCRIPT'
          import smtplib
          import os
          from email.mime.multipart import MIMEMultipart
          from email.mime.text import MIMEText
          
          # Email configuration from secrets
          smtp_server = os.environ.get('EMAIL_SERVER', 'smtp.gmail.com')
          smtp_port = int(os.environ.get('EMAIL_PORT', '587'))
          username = os.environ.get('EMAIL_USERNAME')
          password = os.environ.get('EMAIL_PASSWORD')
          from_addr = os.environ.get('EMAIL_FROM', username)
          to_addrs = os.environ.get('EMAIL_TO', '').split(',')
          repository = os.environ.get('GITHUB_REPOSITORY', 'Repository')
          
          # Read HTML content
          with open('rss-output.html', 'r') as f:
              html_content = f.read()
          
          # Create message
          msg = MIMEMultipart('alternative')
          msg['Subject'] = f'📰 RSS Feed Updates - {repository}'
          msg['From'] = from_addr
          msg['To'] = ', '.join(to_addrs)
          
          # Attach HTML content
          html_part = MIMEText(html_content, 'html')
          msg.attach(html_part)
          
          # Send email
          try:
              with smtplib.SMTP(smtp_server, smtp_port) as server:
                  server.starttls()
                  server.login(username, password)
                  server.send_message(msg)
                  print(f"Email sent successfully to {', '.join(to_addrs)}")
          except Exception as e:
              print(f"Failed to send email: {e}")
              exit(1)
          
          PYTHON_SCRIPT
        env:
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      
      - name: Display results summary
        if: always()
        run: |
          echo "## RSS Feed Collection Summary (Email)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f rss-output.md ]; then
            cat rss-output.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No results generated" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rss-feed-results-email
          path: |
            rss-output.json
            rss-output.md
            rss-output.html
          retention-days: 7
