name: RSS Feed Collector (Slack)

# This workflow is disabled by default. To enable it:
# 1. Uncomment the 'on:' section below
# 2. Configure the SLACK_WEBHOOK_URL secret
# 3. Optionally disable the default MS Teams workflow

# on:
#   # Run on push to any branch
#   push:
#     branches:
#       - '**'
#   
#   # Schedule to run on weekdays at 9 AM UTC
#   schedule:
#     - cron: '0 9 * * 1-5'  # Monday-Friday at 9 AM UTC
#   
#   # Allow manual trigger
#   workflow_dispatch:

on:
  # Only allow manual trigger by default
  workflow_dispatch:

permissions:
  contents: read

jobs:
  collect-rss-feeds-slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Get last successful run time
        id: last-run
        run: |
          # Get the current date
          TODAY=$(date -u +%Y-%m-%d)
          
          # Try to get the last successful run time from this workflow
          LAST_RUN=$(gh run list \
            --workflow="rss-feed-collector-slack.yml" \
            --status=success \
            --limit=1 \
            --json updatedAt \
            --jq '.[0].updatedAt' 2>/dev/null || echo "")
          
          if [ -n "$LAST_RUN" ]; then
            LAST_RUN_DATE=$(date -u -d "$LAST_RUN" +%Y-%m-%d)
            LAST_RUN_EPOCH=$(date -u -d "$LAST_RUN" +%s)
            NOW_EPOCH=$(date -u +%s)
            HOURS_SINCE=$((($NOW_EPOCH - $LAST_RUN_EPOCH) / 3600))
            
            # If last run was today, use 24 hours, otherwise use hours since last run
            if [ "$LAST_RUN_DATE" = "$TODAY" ]; then
              echo "hours=24" >> $GITHUB_OUTPUT
              echo "Last successful run was today, fetching articles from last 24 hours"
            else
              # Cap at 168 hours (1 week) to avoid too much data
              if [ $HOURS_SINCE -gt 168 ]; then
                HOURS_SINCE=168
              fi
              echo "hours=$HOURS_SINCE" >> $GITHUB_OUTPUT
              echo "Last successful run was $HOURS_SINCE hours ago, fetching articles since then"
            fi
          else
            # No previous successful run, default to 24 hours
            echo "hours=24" >> $GITHUB_OUTPUT
            echo "No previous successful run found, fetching articles from last 24 hours"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Fetch RSS feeds
        run: |
          python .github/scripts/fetch_rss_feeds.py \
            --config .github/rss-feeds.json \
            --hours ${{ steps.last-run.outputs.hours }} \
            --output rss-output.json \
            --markdown-output rss-output.md
      
      - name: Send to Slack
        if: secrets.SLACK_WEBHOOK_URL != ''
        run: |
          # Read the markdown content
          MARKDOWN_CONTENT=$(cat rss-output.md)
          
          # Convert markdown to Slack blocks format
          # Create a simple text block with the markdown content
          # Slack supports mrkdwn format which is similar to markdown
          
          # Escape special characters for JSON
          ESCAPED_CONTENT=$(echo "$MARKDOWN_CONTENT" | jq -Rs .)
          
          # Create Slack message JSON
          cat > slack-message.json << EOF
          {
            "text": "RSS Feed Updates",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "📰 RSS Feed Updates"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": $ESCAPED_CONTENT
                }
              }
            ]
          }
          EOF
          
          # Send to Slack
          curl -X POST \
            -H "Content-Type: application/json" \
            -d @slack-message.json \
            "${{ secrets.SLACK_WEBHOOK_URL }}"
      
      - name: Display results summary
        if: always()
        run: |
          echo "## RSS Feed Collection Summary (Slack)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f rss-output.md ]; then
            cat rss-output.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No results generated" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rss-feed-results-slack
          path: |
            rss-output.json
            rss-output.md
          retention-days: 7
