# GitHub Copilot Setup Steps
# This file configures the environment for GitHub Copilot Workspace
# Documentation: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

setup_steps:
  # Python dependencies
  - name: Install Python dependencies
    command: pip install feedparser pytest
    description: Install required Python packages for RSS feed collection and testing
  
  # JavaScript/Node.js dependencies
  - name: Install Node.js dependencies
    command: npm install
    description: Install Jest and testing dependencies for JavaScript unit tests
  
  # Verify installations
  - name: Verify Python setup
    command: python3 --version && pip list | grep -E "feedparser|pytest"
    description: Verify Python and required packages are installed
  
  - name: Verify Node.js setup
    command: node --version && npm --version && npm list --depth=0
    description: Verify Node.js, npm, and installed packages
