name: 'Collect RSS Feeds'
description: 'Collects articles from RSS/Atom feeds and outputs results as JSON'
author: 'GitHub Copilot'

inputs:
  config-path:
    description: 'Path to the RSS feeds configuration JSON file'
    required: false
    default: '.github/rss-feeds.json'
  hours:
    description: 'Fetch articles from the last N hours'
    required: false
    default: '24'
  output-path:
    description: 'Path where the output JSON file will be saved'
    required: false
    default: 'rss-feeds-output.json'

outputs:
  output-file:
    description: 'Path to the generated JSON output file'
    value: ${{ steps.collect.outputs.output-file }}
  total-articles:
    description: 'Total number of articles collected'
    value: ${{ steps.collect.outputs.total-articles }}
  successful-feeds:
    description: 'Number of successfully fetched feeds'
    value: ${{ steps.collect.outputs.successful-feeds }}
  failed-feeds:
    description: 'Number of failed feeds'
    value: ${{ steps.collect.outputs.failed-feeds }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install feedparser
    
    - name: Collect RSS feeds
      id: collect
      shell: bash
      run: |
        python3 ${{ github.action_path }}/collect_feeds.py \
          --config "${{ inputs.config-path }}" \
          --hours ${{ inputs.hours }} \
          --output "${{ inputs.output-path }}"
        
        # Set outputs
        echo "output-file=${{ inputs.output-path }}" >> $GITHUB_OUTPUT
        
        # Extract summary information from the JSON
        if [ -f "${{ inputs.output-path }}" ]; then
          TOTAL_ARTICLES=$(jq -r '.summary.total_articles' "${{ inputs.output-path }}")
          SUCCESSFUL_FEEDS=$(jq -r '.summary.successful_feeds' "${{ inputs.output-path }}")
          FAILED_FEEDS=$(jq -r '.summary.failed_feeds' "${{ inputs.output-path }}")
          
          echo "total-articles=$TOTAL_ARTICLES" >> $GITHUB_OUTPUT
          echo "successful-feeds=$SUCCESSFUL_FEEDS" >> $GITHUB_OUTPUT
          echo "failed-feeds=$FAILED_FEEDS" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate summary
      shell: bash
      run: |
        # Generate markdown summary for GitHub workflow
        python3 ${{ github.action_path }}/generate_summary.py \
          --input "${{ inputs.output-path }}" \
          --markdown /tmp/summary.md
        
        # Append markdown summary to GitHub Step Summary
        cat /tmp/summary.md >> $GITHUB_STEP_SUMMARY
        
        echo "Summary generated successfully"
