name: 'Collect RSS Feeds'
description: 'Collects articles from RSS/Atom feeds and outputs results as JSON'
author: 'GitHub Copilot'

inputs:
  config-path:
    description: 'Path to the RSS feeds configuration JSON file'
    required: false
    default: '.github/rss-feeds.json'
  hours:
    description: 'Fetch articles from the last N hours'
    required: false
    default: '24'
  output-path:
    description: 'Path where the output JSON file will be saved'
    required: false
    default: 'rss-feeds-output.json'

outputs:
  output-file:
    description: 'Path to the generated JSON output file'
    value: ${{ steps.collect.outputs.output-file }}
  total-articles:
    description: 'Total number of articles collected'
    value: ${{ steps.collect.outputs.total-articles }}
  successful-feeds:
    description: 'Number of successfully fetched feeds'
    value: ${{ steps.collect.outputs.successful-feeds }}
  failed-feeds:
    description: 'Number of failed feeds'
    value: ${{ steps.collect.outputs.failed-feeds }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install feedparser
    
    - name: Collect RSS feeds
      id: collect
      shell: bash
      run: |
        python3 ${{ github.action_path }}/collect_feeds.py \
          --config "${{ inputs.config-path }}" \
          --hours ${{ inputs.hours }} \
          --output "${{ inputs.output-path }}"
        
        # Set outputs
        echo "output-file=${{ inputs.output-path }}" >> $GITHUB_OUTPUT
        
        # Extract summary information from the JSON
        if [ -f "${{ inputs.output-path }}" ]; then
          TOTAL_ARTICLES=$(jq -r '.summary.total_articles' "${{ inputs.output-path }}")
          SUCCESSFUL_FEEDS=$(jq -r '.summary.successful_feeds' "${{ inputs.output-path }}")
          FAILED_FEEDS=$(jq -r '.summary.failed_feeds' "${{ inputs.output-path }}")
          
          echo "total-articles=$TOTAL_ARTICLES" >> $GITHUB_OUTPUT
          echo "successful-feeds=$SUCCESSFUL_FEEDS" >> $GITHUB_OUTPUT
          echo "failed-feeds=$FAILED_FEEDS" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate summary
      shell: bash
      run: |
        python3 << 'PYTHON_SCRIPT'
        import json
        import os
        
        output_file = "${{ inputs.output-path }}"
        
        # Read the JSON output
        with open(output_file, 'r') as f:
            data = json.load(f)
        
        # Generate markdown summary
        summary = []
        summary.append("# 📰 RSS Feed Collection Summary\n")
        summary.append(f"**Collected at:** {data['metadata']['collected_at']}\n")
        summary.append(f"**Time range:** Last {data['metadata']['hours']} hours\n")
        summary.append("")
        
        # Overall summary
        summary.append("## 📊 Summary\n")
        summary.append(f"- **Total feeds:** {data['summary']['total_feeds']}")
        summary.append(f"- **Successful:** {data['summary']['successful_feeds']}")
        summary.append(f"- **Failed:** {data['summary']['failed_feeds']}")
        summary.append(f"- **Total articles:** {data['summary']['total_articles']}")
        summary.append("")
        
        # Successful feeds
        if data['feeds']:
            summary.append("## ✅ Successful Feeds\n")
            for feed_name, feed_data in data['feeds'].items():
                summary.append(f"### {feed_name}")
                summary.append(f"- **Articles:** {feed_data['count']}")
                
                if feed_data['articles']:
                    summary.append("\n| Title | Published |")
                    summary.append("|-------|-----------|")
                    for article in feed_data['articles'][:10]:  # Limit to first 10
                        title = article['title'][:80] + "..." if len(article['title']) > 80 else article['title']
                        published = article['published']
                        summary.append(f"| [{title}]({article['link']}) | {published} |")
                    
                    if feed_data['count'] > 10:
                        summary.append(f"\n*...and {feed_data['count'] - 10} more articles*")
                else:
                    summary.append("*No new articles*")
                
                summary.append("")
        
        # Failed feeds
        if data['failed_feeds']:
            summary.append("## ❌ Failed Feeds\n")
            summary.append("| Feed Name | URL |")
            summary.append("|-----------|-----|")
            for failed in data['failed_feeds']:
                summary.append(f"| {failed['name']} | {failed['url']} |")
            summary.append("")
        
        # Write to GitHub Step Summary
        summary_text = '\n'.join(summary)
        
        with open(os.environ['GITHUB_STEP_SUMMARY'], 'a') as f:
            f.write(summary_text)
        
        print("Summary generated successfully")
        
        PYTHON_SCRIPT
