name: ♻️ Code Refactor
description: Suggest code improvements or refactoring
title: "[Refactor]: "
labels: ["refining", "refactor"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the code quality! Please describe the refactoring you'd like to suggest.

  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: Describe the current code or structure that needs refactoring.
      placeholder: Currently, the code...
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Describe how you'd like to refactor or improve the code.
      placeholder: I suggest refactoring to...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this refactoring?
      placeholder: |
        - Improved readability
        - Better performance
        - Reduced code duplication
        - Easier maintenance
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this refactoring affect?
      options:
        - RSS Feed Collection (Python)
        - UI/Frontend (JavaScript/HTML/CSS)
        - GitHub Actions Workflow
        - Shell Scripts
        - Testing Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How extensive is this refactoring?
      options:
        - Small - Single file or function
        - Medium - Multiple files or components
        - Large - Significant architectural change
    validations:
      required: true

  - type: textarea
    id: files-affected
    attributes:
      label: Files/Components Affected
      description: List the files or components that would be affected by this refactoring.
      placeholder: |
        - `path/to/file1.js`
        - `path/to/file2.py`
    validations:
      required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Does this refactoring involve breaking changes?
      options:
        - label: This refactoring may introduce breaking changes
          required: false

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any specific notes about how this should be implemented?
      placeholder: Consider using... Make sure to...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or references here.
      placeholder: Links to documentation, similar implementations, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Before submitting, please verify the following
      options:
        - label: I have searched existing issues to ensure this refactoring has not already been suggested
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: I have read the [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
